# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SendToSprite < Formula
  desc "Send clipboard contents (screenshots, text, files) to a Sprite"
  homepage "https://github.com/spritetools/send-to-sprite"
  version "0.1.0"
  license "MIT"

  depends_on "pngpaste"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/spritetools/send-to-sprite/releases/download/v0.1.0/send-to-sprite_darwin_amd64.tar.gz"
    sha256 "67103bc509b30088a9edfb2dcfb247fdd1a3a6c10f35efaf695258e9b5cf36fb"

    define_method(:install) do
      bin.install "send-to-sprite"
      prefix.install "apps/Send to Sprite.app"
      prefix.install "apps/Send Capture to Sprite.app"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/spritetools/send-to-sprite/releases/download/v0.1.0/send-to-sprite_darwin_arm64.tar.gz"
    sha256 "73b2d8c428e74a95cac9f321507c106e8b3136aa7f604808f128b77ca6af1798"

    define_method(:install) do
      bin.install "send-to-sprite"
      prefix.install "apps/Send to Sprite.app"
      prefix.install "apps/Send Capture to Sprite.app"
    end
  end

  def caveats
    <<~EOS
      To make the apps available in Spotlight, symlink them to /Applications:
        ln -sf "#{prefix}/Send to Sprite.app" /Applications/
        ln -sf "#{prefix}/Send Capture to Sprite.app" /Applications/

      Then you can launch them with Cmd+Space → "Send to Sprite" or "Send Capture to Sprite".
    EOS
  end
end
